### ISSUE TITLE
主板型号

### ISSUE THREAD

**Issue by blue0121** [zyb23122/i5-12400-B660M-EFI#1]
请问主板型号是什么？

**Comment by zyb23122** [comment]
主板型号为 装机员B660一号，其实是华硕B660换皮，B660芯片应该都可以用，和芯片组有关




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zyb23122/i5-12400-B660M-EFI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月7日(星期四) 上午10:30
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zyb23122/i5-12400-B660M-EFI] 主板型号 (Issue #1)





 
请问主板型号是什么？
